name = "aptosdefihub"
main = "src/worker.ts"
compatibility_date = "2025-05-05"

[dev]
port = 3000

[triggers]
crons = ["*/5 * * * *"]  # Every 10 minutes (UTC)

# KV bindings for user address tracking
[[kv_namespaces]]
binding = "USER_ADDRESSES"
id = "YOUR_PRODUCTION_KV_ID_HERE"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
